disabled_rules:
  - identifier_name
  - force_try
  - force_cast
  - function_parameter_count
  - blanket_disable_command
  - opening_brace
  - trailing_comma

included:
  - Sources
  - Tests

excluded:
  - Tests/LicensePlistTests/XcodeProjects
  - Tests/LicensePlistTests/Resources

line_length: 250
nesting:
  type_level: 3
