disabled_rules:
  - identifier_name
  - force_try
  - force_cast
  - function_parameter_count

included:
  - Sources
  - Tests
  
excluded:
  - Tests/LicensePlistTests/XcodeProjects
  - Tests/LicensePlistTests/Entity/FileReader/XcodeProjectFileReaderTests.swift

line_length: 250
nesting:
  type_level: 3
